### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by jedisct1** [angt/glorytun-openwrt#3]
This repository needs some love.

Everybody does.

**Comment by angt** [comment]
I will :)
Waiting for that you can give a try to http://downloads.overthebox.net/develop.
Current master is only based on glorytun (no mptcp/shadowsocks).
Also, it easy to setup a custom server with `otb-configure-glorytun`.

**Comment by jedisct1** [comment]
The lousy part is having these builds for non-x86_64 architectures :/

**Comment by angt** [comment]
rpi 3 ?

**Comment by angt** [comment]
First draft: f1bbbe138473fcdcc4c2d170a3e0cccd7dca8189
Not tested yet.

**Comment by jedisct1** [comment]
mips

**Comment by angt** [comment]
For example, it is very easy to compile a `mipsel32` image with [overthebox](https://github.com/ovh/overthebox):
```OTB_TARGET=mipsel32 sh build.sh```

**Comment by angt** [comment]
If your arch is not supported, just put your 3 lines config file in `config` :)
