### ISSUE TITLE
libsodium >= 1.0.4 requirement.  (is 1.0.2 good enough?)

### ISSUE THREAD

**Issue by triple-it** [angt/glorytun-openwrt#4]
I see it is also mentioned in the readme
~~
**You need an OpenWrt version with libsodium >= 1.0.4.**
~~

But could we lower the requirement not to 1.0.2, which is more mainstream...

e.g. during configure stage
~~
requested 'libsodium >= 1.0.4' but version of libsodium is 1.0.2
~~

Repo:
triple_admin@triplemobile6zotac1:~/openwrt-cc$ git config --get remote.origin.url
https://github.com/domino-team/openwrt-cc.git
triple_admin@triplemobile6zotac1:~/openwrt-cc$

**Comment by angt** [comment]
Hi,
I think version 1.0.4 is no longer required but you should try to update libsodium instead :)
Regards.
